import {BiAlignLeft} from 'react-icons/bi';
const routesConfig = [
  {
    id: 'app',
    title: 'Sample',
    messageId: 'Payments',
    type: 'collapse',
    children: [
      {
        id: 'payment',
        title: 'Payment',
        messageId: 'Payment',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/Invoice',
      },
      {
        id: 'checkout',
        title: 'Checkout',
        messageId: 'Checkout',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/CheckoutForm',
      },
      {
        id: 'checkout',
        title: 'Payment Setup',
        messageId: 'Payment Setup',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/PaymentSetup',
      },
      {
        id: 'payment-details',
        title: 'Payment Details',
        messageId: 'Payment Details',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/PaymentDetails',
      },
    ],
  },
  {
    id: 'app',
    title: 'Sample',
    messageId: 'Documents',
    type: 'collapse',
    children: [
      {
        id: 'document-upload',
        title: 'Document Upload',
        messageId: 'Document Upload',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/DocumentUpload',
      },
      {
        id: 'document-view',
        title: 'Document View',
        messageId: 'Document View',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/DocumentView',
      },
    ]
  },
  {
    id: 'app',
    title: 'Sample',
    messageId: 'Plannings',
    type: 'collapse',
    children: [
      {
        id: 'create-appointment',
        title: 'Create Appointment',
        messageId: 'Create Appointment',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/CreateAppointment',
      },
      {
        id: 'menu-planning',
        title: 'Menu Planning',
        messageId: 'Menu Planning',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/MenuPlanning',
      },
      {
        id: 'learning',
        title: 'Learning',
        messageId: 'Learning',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/Learning',
      },
      {
        id: 'school-events',
        title: 'School Events',
        messageId: 'School Events',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/EventCalendar',
      },
      {
        id: 'tenant-plan',
        title: 'Tenant Plan',
        messageId: 'Tenant Plan',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/TenantPlan',
      },
    ]
  },
  {
    id: 'app',
    title: 'Sample',
    messageId: 'Albmus',
    type: 'collapse',
    children: [
      {
        id: 'albums',
        title: 'Albums',
        messageId: 'Albums',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/Albums',
      },
      {
        id: 'activity-upload',
        title: 'Activity Upload',
        messageId: 'Activity Upload',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/ActivityMediaUpload',
      },
    ]
  },
  {
    id: 'app',
    title: 'Sample',
    messageId: 'Surveys',
    type: 'collapse',
    children: [
      {
        id: 'survey-editor',
        title: 'Survey Editor',
        messageId: 'Survey Editor',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/SurveyEditor',
      },
      {
        id: 'survey-settings',
        title: 'Survey Settings',
        messageId: 'Survey Settings',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/SurveySettings',
      },
    ]
  },
  {
    id: 'app',
    title: 'Sample',
    messageId: 'Checks',
    type: 'collapse',
    children: [
      {
        id: 'sleep-check',
        title: 'Sleep Check',
        messageId: 'Sleep Check',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/SleepCheck',
      },
      {
        id: 'health-check',
        title: 'Health Check',
        messageId: 'Health Check',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/HealthCheck',
      },
      {
        id: 'toilet-check',
        title: 'Toilet Check',
        messageId: 'Toilet Check',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/ToiletCheck',
      },
    ]
  },
  {
    id: 'app',
    title: 'Sample',
    messageId: 'Forms',
    type: 'collapse',
    children: [
      {
        id: 'survey-form',
        title: 'Addmission Form',
        messageId: 'Addmission Form',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/AddmissionForm',
      },
      {
        id: 'activities-form',
        title: 'Activities Form',
        messageId: 'Activities Form',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/ActivitiesForm',
      },
      {
        id: 'injuries-form',
        title: 'Injuries Form',
        messageId: 'Injuries Form',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/InjuriesForm',
      },
      {
        id: 'injuries-form',
        title: 'Charges Form',
        messageId: 'Charges Form',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/ChargesForm',
      },
      {
        id: 'appointment-form',
        title: 'Appointment Form',
        messageId: 'Appointment Form',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/AppointmentForm',
      },
      {
        id: 'tax-form',
        title: 'Tax Form',
        messageId: 'Tax Form',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/TaxForm',
      },
      {
        id: 'leave-application-form',
        title: 'Leave Application Form',
        messageId: 'Leave Application Form',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/LeaveApplicationForm',
      },
    ]
  },
  {
    id: 'app',
    title: 'Sample',
    messageId: 'Room Report',
    type: 'collapse',
    children: [
      {
        id: 'check-in-report',
        title: 'Check-in Report',
        messageId: 'Check-in Report',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/Check-inReport',
      },
      {
        id: 'room-check-report',
        title: 'Room Check Report',
        messageId: 'Room Check Report',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/RoomCheckReport',
      },
      {
        id: 'immunization-report',
        title: 'Immunization Report',
        messageId: 'Immunization Report',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/ImmunizationReport',
      },
      {
        id: 'immunization',
        title: 'Immunization',
        messageId: 'Immunization',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/Immunization',
      },
      {
        id: 'react-data-grid-report',
        title: 'React Data Grid Report',
        messageId: 'React Data Grid Report',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/ReactDataGridReport',
      },
    ]
  },
  {
    id: 'app',
    title: 'Data Migration',
    messageId: 'Data Migration',
    type: 'collapse',
    children: [
      {
        id: 'import-csv',
        title: 'Import CSV',
        messageId: 'Import CSV',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/ImportCSV',
      },
      {
        id: 'data-migration',
        title: 'Data Migration',
        messageId: 'Data Migration',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/Migration',
      },
    ]
  },
  {
    id: 'app',
    title: 'Sample',
    messageId: 'Others',
    type: 'collapse',
    children: [
      {
        id: 'scheduler-settings',
        title: 'Scheduler Settings',
        messageId: 'Scheduler Settings',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/SchedulerSettings',
      },
      {
        id: 'pdf-download',
        title: 'PDF Download',
        messageId: 'PDF Download',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/PDFDownload',
      },
      {
        id: 'email-editor',
        title: 'Email Editor',
        messageId: 'Email Editor',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/EmailEditor',
      },
      {
        id: 'annoucement-editor',
        title: 'Annoucement Editor',
        messageId: 'Annoucement Editor',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/HtmlEditors',
      },
      {
        id: 'button-test',
        title: 'Button Test',
        messageId: 'Button Test',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/ButtonTest',
      },
      {
        id: 'audit-log',
        title: 'Audit Log',
        messageId: 'Audit Log',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/AuditLog',
      },
    ]
  },
];
export default routesConfig;
